// import chooseLiveQrcode from '@youzan/react-components/es/components/choose-dialog/dialogs/live-qrcode';
import {
  Dialog,
  // EasyList,
  Select,
  // EasyForm,
  // LockWrap,
  EditFormHoc,
  TempAlertInfo,
  ListPopupEditor,
  Img,
  PopEllipsisText,
  MouseFollow,
  LinkGroup,
  OrderTable,
  TimingTask,
  CustomSelector
} from '@youzan/ebiz-components';

// import {
//   // equal or more than 2 times
//   Upload,
//   BlankLink,
//   Operations,
//   RegionSelect,
//   CouponSelector,
//   ChooseDialog,
//   BreadcrumbNav,
//   UmpAppBoardV2,
//   VideoUpload,
//   DisplayBoard,
//   GoodsSelector,
//   Richtext,
//   PopSku,
//   Divider,
//   MultiCascader,
// } from '@youzan/react-components';

// 通过unused校验
console.log({
  Dialog,
  // EasyList,
  Select,
  // EasyForm,
  // LockWrap,
  EditFormHoc,
  TempAlertInfo,
  ListPopupEditor,
  Img,
  PopEllipsisText,
  MouseFollow,
  LinkGroup,
  OrderTable,
  TimingTask,
  CustomSelector,
  // Upload,
  // BlankLink,
  // Operations,
  // RegionSelect,
  // CouponSelector,
  // ChooseDialog,
  // BreadcrumbNav,
  // UmpAppBoardV2,
  // VideoUpload,
  // DisplayBoard,
  // GoodsSelector,
  // Richtext,
  // PopSku,
  // Divider,
  // MultiCascader,
  // chooseLiveQrcode,
});
