export const PAY_STATE = {
  CREATED: 1,
  WAIT_PAY: 10,
  PAID: 20,
  CLOSED: 99,
};

export const mutations = {
  UPDATE_PAY_STATE_TEXT: 'UPDATE_PAY_STATE_TEXT',
  UPDATE_TIP: 'UPDATE_TIP',
  UPDATE_PAY_STATE: 'UPDATE_PAY_STATE',
  UPDATE_PAY_REWARD_INFO: 'UPDATE_PAY_REWARD_INFO',
  UPDATE_ACTIVITIES_INFO: 'UPDATE_ACTIVITIES_INFO',
  UPDATE_SHOW_RECOMMEND: 'UPDATE_SHOW_RECOMMEND',
  UPDATE_BTN_LIST: 'UPDATE_BTN_LIST',
  UPDATE_BTN_UMP_MAP: 'UPDATE_BTN_UMP_MAP',
  UPDATE_PAY_SUCCESS_TEXT: 'UPDATE_PAY_SUCCESS_TEXT',
};

export const REWARD_STATUS = {
  UNRECEIVED: 1,
  RECEIVED: 3,
};

export const REWARD_TYPE = {
  COUPON: 1,
  COURSE: 2,
  EXP_COURSE: 3,
  POINTS: 4,
};
