export = [
  [
    "GET",
    "/wscvis/course/live/live-selling/findCouponList.json",
    "course.live.LiveSellingController",
    "getFindCouponListJson",
  ],
  [
    "POST",
    "/wscvis/course/live/live-selling/receiveCoupon.json",
    "course.live.LiveSellingController",
    "postReceiveCouponJson",
  ],
  [
    "GET",
    "/wscvis/course/live/live-selling/findGoodsList.json",
    "course.live.LiveSellingController",
    "getFindPageJson",
  ],
  [
    "GET",
    "/wscvis/course/live/live-selling/getLiveMarketingSetting.json",
    "course.live.LiveSellingController",
    "getGetLiveMarketingSettingJson",
  ],
];
