module.exports = [
  [
    'GET',
    '/v4/vis/stat/consume',
    'other.stat.ConsumeStatController',
    'getIndexHtml',
  ],
  [
    'GET',
    '/v4/vis/stat/consume/getConsumeClassOverview.json',
    'other.stat.ConsumeStatController',
    'getConsumeClassOverview',
  ],
  [
    'GET',
    '/v4/vis/stat/consume/findConsumeClassDetailPage.json',
    'other.stat.ConsumeStatController',
    'findConsumeClassDetailPage',
  ],
  [
    'POST',
    '/v4/vis/stat/consume/exportConsumeClassDetail.json',
    'other.stat.ConsumeStatController',
    'exportConsumeClassDetail',
  ],
];
