module.exports = [
  [
    'GET',
    '/v4/vis/edu/page/courseStat',
    'other.stat.CourseStatController',
    'getIndexHtml',
  ],
  [
    'GET',
    '/v4/vis/edu/courseStat/getOverview.json',
    'other.stat.CourseStatController',
    'getOverview',
  ],
  [
    'GET',
    '/v4/vis/edu/courseStat/getCoursePaidAmount.json',
    'other.stat.CourseStatController',
    'getCoursePaidAmount',
  ],
  [
    'GET',
    '/v4/vis/edu/courseStat/getStudentPaidAmount.json',
    'other.stat.CourseStatController',
    'getStudentPaidAmount',
  ],
  [
    'GET',
    '/v4/vis/edu/courseStat/findCourseAssetPaidByPage.json',
    'other.stat.CourseStatController',
    'findCourseAssetPaidByPage',
  ],
  [
    'GET',
    '/v4/vis/edu/courseStat/findCourseAssetPaidTotal.json',
    'other.stat.CourseStatController',
    'findCourseAssetPaidTotal',
  ],
];
