// 考试
module.exports = [
  [
    // 页面render
    'GET',
    '/v4/vis/supv/examination',
    'supv.ExaminationController',
    ['initLifecycle', 'setPluginInfo', 'getIndexHtml'],
  ],
  [
    'GET',
    '/v4/vis/supv/examination/initExamPlugin.json',
    'supv.ExaminationController',
    'initExamPlugin',
  ],
  [
    'POST',
    '/v4/vis/supv/examination/findPaperQuestions.json',
    'supv.ExaminationController',
    'findPaperQuestions',
  ],
  [
    'POST',
    '/v4/vis/supv/examination/_textarea_/createExamTemplate.json',
    'supv.ExaminationController',
    'createExamTemplate',
  ],
  [
    'POST',
    '/v4/vis/supv/examination/_textarea_/updateExamTemplate.json',
    'supv.ExaminationController',
    'updateExamTemplate',
  ],
  [
    'POST',
    '/v4/vis/supv/examination/createExamPaper.json',
    'supv.ExaminationController',
    'createExamPaper',
  ],
  [
    'GET',
    '/v4/vis/supv/examination/getExamTemplateDetail.json',
    'supv.ExaminationController',
    'getExamTemplateDetail',
  ],
  [
    'GET',
    '/v4/vis/supv/examination/getExamPaperDetail.json',
    'supv.ExaminationController',
    'getExamPaperDetail',
  ],
  [
    'GET',
    '/v4/vis/supv/examination/findPage.json',
    'supv.ExaminationController',
    'findPage',
  ],
  [
    'POST',
    '/v4/vis/supv/examination/quickUpdate.json',
    'supv.ExaminationController',
    'quickUpdate',
  ],
  [
    'POST',
    '/v4/vis/supv/examination/deleteExam.json',
    'supv.ExaminationController',
    'deleteExam',
  ],
  [
    'GET',
    '/v4/vis/supv/examination/countJoinUsers.json',
    'supv.ExaminationController',
    'countJoinUsers',
  ],
  /** ----------- 批阅接口 ----------- */
  [
    'GET',
    '/v4/vis/supv/examination/findByReview.json',
    'supv.ExaminationController',
    'findByReview',
  ],
  [
    'GET',
    '/v4/vis/supv/examination/getReviewDetail.json',
    'supv.ExaminationController',
    'getReviewDetail',
  ],
  [
    'POST',
    '/v4/vis/supv/examination/submitReview.json',
    'supv.ExaminationController',
    'submitReview',
  ],
  [
    'GET',
    '/v4/vis/supv/examination/getReviewIdByOption.json',
    'supv.ExaminationController',
    'getReviewIdByOption',
  ],

  /*
   +---------------------------------------+
   |              统计分析                  |
   +--------------------------------------+
  */

  [
    'GET',
    '/v4/vis/supv/examination/getBaseStatById.json',
    'supv.ExaminationController',
    'getBaseStatById',
  ],
  [
    'GET',
    '/v4/vis/supv/examination/findListStageStatById.json',
    'supv.ExaminationController',
    'findListStageStatById',
  ],
  [
    'GET',
    '/v4/vis/supv/examination/findPageQuestionStatById.json',
    'supv.ExaminationController',
    'findPageQuestionStatById',
  ],
  [
    'GET',
    '/v4/vis/supv/examination/getOptionStatById.json',
    'supv.ExaminationController',
    'getOptionStatById',
  ],
  [
    'GET',
    '/v4/vis/supv/examination/findPageUserStat.json',
    'supv.ExaminationController',
    'findPageUserStat',
  ],
  [
    'GET',
    '/v4/vis/supv/examination/getExamUserCollectionInfo.json',
    'supv.ExaminationController',
    'getExamUserCollectionInfo',
  ],
  [
    'POST',
    '/v4/vis/supv/examination/exportUserStat.json',
    'supv.ExaminationController',
    'exportUserStat',
  ]
];
