export const themeColor = {
  'black-white-theme': '#2f2f34',
  'blue-theme': '#4a90e2',
  'brown-theme': '#c3a769',
  'default-theme': '#f44',
  'fantasy-theme': '#9a875f',
  'gold-theme': '#fcc600',
  'green-black-theme': '#09bb07',
  'haitao-theme': '#884cff',
  'light-green-theme': '#65c4aa',
  'middle-green-theme': '#63be72',
  'orange-theme': '#ff5e15',
  'pink-theme': '#ff547b',
  'red-black-theme': '#f44',
  'red-linear-theme': '#ee0a24',
};

export const themeTypeMap = {
  '0': 'default-theme',
  '1': 'orange-theme',
  '2': 'pink-theme',
  '3': 'red-black-theme',
  '4': 'gold-theme',
  '5': 'light-green-theme',
  '6': 'green-black-theme',
  '7': 'middle-green-theme',
  '8': 'blue-theme',
  '9': 'brown-theme',
  '10': 'black-white-theme',
  '11': 'fantasy-theme',
  '12': 'haitao-theme',
  '13': 'red-linear-theme',
};

export const viceThemeColor = {
  'black-white-theme': '#ebecf2',
  'blue-theme': '#dbe9f9',
  'brown-theme': '#f3eee1',
  'default-theme': '#f85',
  'fantasy-theme': '#9a875f',
  'gold-theme': '#1d262e',
  'green-black-theme': '#383838',
  'haitao-theme': '#efe6ff',
  'light-green-theme': '#ddf2ec',
  'middle-green-theme': '#e1f4e3',
  'orange-theme': '#ff9300',
  'pink-theme': '#ffe6e8',
  'red-black-theme': '#555',
  'red-linear-theme': '#ffd01e',
};
