export = [
  [
    "POST",
    "/wscvis/ump/tuition/collectZan.json",
    "ump.TuitionController",
    "postCollectZanJson"
  ],
  [
    "GET",
    "/wscvis/ump/tuition/getDetail.json",
    "ump.TuitionController",
    "getGetDetailJson"
  ],
  [
    "GET",
    "/wscvis/ump/tuition/listLatestRollingText.json",
    "ump.TuitionController",
    "getListLatestRollingTextJson"
  ],
  [
    "POST",
    "/wscvis/ump/tuition/participate.json",
    "ump.TuitionController",
    "postParticipateJson"
  ],
  [
    "GET",
    "/wscvis/ump/tuition/listHelperPaged.json",
    "ump.TuitionController",
    "getListHelperPagedJson"
  ],
  [
    "GET",
    "/wscvis/ump/tuition/listGoodsPaged.json",
    "ump.TuitionController",
    "getListGoodsPagedJson"
  ],

  [
    "POST",
    "/wscvis/ump/tuition/listAttributeByIdList.json",
    "ump.TuitionController",
    "getListAttributeByIdListJson"
  ],
  [
    "GET",
    "/wscvis/ump/tuition/getUserHelpStatus.json",
    "ump.TuitionController",
    "getGetUserHelpStatusJson"
  ],

  [
    "GET",
    "/wscvis/ump/tuition/findGoodsByPage.json",
    "ump.TuitionController",
    "getFindGoodsByPageJson"
  ],

  [
    "POST",
    "/wscvis/ump/tuition/sendVerifyCode.json",
    "ump.TuitionController",
    "postSendVerifyCodeJson"
  ],

  /** 恶魔退散 */
  [
    "GET",
    "/wscvis/ump/tuition/:alias",
    "ump.TuitionController",
    "renderLandingPage"
  ]
];
