import {
  ExamStatus,
  UserExamStatus,
  OwlType,
  MediaType,
  QuestionType,
} from '../types';

export const getDetailData = Promise.resolve({
  collectSetting: [{ 'attrItem': [], 'attributeId': 379, 'attributeKey': 'edu_stuName', 'attributeTags': ['edu_stuName'], 'attributeTitle': '学员姓名', 'attributeType': 2, 'canDel': false, 'createdAt': 1551237415000, 'dataType': 0, 'needFill': true, 'placeholder': '', 'serialNo': 1003, 'showDefault': false }, { 'attrItem': [], 'attributeId': 380, 'attributeKey': 'edu_stuBirth', 'attributeTags': ['edu_stuBirth'], 'attributeTitle': '学员生日', 'attributeType': 2, 'canDel': false, 'createdAt': 1551237416000, 'dataType': 2, 'needFill': true, 'placeholder': '', 'serialNo': 0, 'showDefault': false }, { 'attrItem': [], 'attributeId': 384, 'attributeKey': 'edu_stuContractPhone', 'attributeTags': ['edu_stuContractPhone'], 'attributeTitle': '联系人手机', 'attributeType': 2, 'canDel': false, 'createdAt': 1551237416000, 'dataType': 9, 'needFill': true, 'placeholder': '', 'serialNo': 0, 'showDefault': false }],
  examDTO: {
    countdownSeconds: 0,
    detail: '<p style="margin-bottom:0px;"><strong>作者简介</strong></p><p><span style="font-size:12px;color:rgb(127 , 127 , 127);">请填写作者简介…</span></p><p style="margin-bottom:0px;"><strong>内容简介</strong></p><p><span style="font-size:12px;color:rgb(127 , 127 , 127);">请填写专栏内容或者价值介绍…</span></p><p style="margin-bottom:0px;"><strong>通过这个专栏，你会得到：</strong></p><p style="margin-top:0px;margin-bottom:0px;"><span style="color:rgb(127 , 127 , 127);font-size:12px;">1、…</span></p><p style="margin-bottom:16px;margin-top:0px;"><span style="color:rgb(127 , 127 , 127);font-size:12px;">2、…</span>↵ &nbsp; &nbsp;<strong><br /></strong>↵ &nbsp;</p><p style="margin-bottom:0px;"><strong>订阅须知</strong></p><p style="margin-bottom:0px;"><span style="color:rgb(127 , 127 , 127);font-size:12px;">↵ &nbsp; &nbsp; &nbsp;1、《请填写本专栏名称》为音频/图文/视频专栏，共计X期,每周一至周<img data-origin-width="750" data-origin-height="1334" src="https://img01.yzcdn.cn/upload_files/2020/05/22/FhZF_L1WgGIRAecju0igi4yVeoOY.png!730x0.jpg" />五的下午7点更新一期; &nbsp; &nbsp;</span>↵ &nbsp;</p><p style="margin-top:0px;margin-bottom:0px;"><span style="margin-top:0px;margin-bottom:0px;color:rgb(127 , 127 , 127);font-size:12px;">↵ &nbsp; &nbsp; &nbsp;2、 每周一至周五的下午7点更新一期，专栏从2018.03.01开始更新，预计2019.03.01完结; &nbsp; &nbsp;</span>↵ &nbsp;</p><p style="margin-top:0px;margin-bottom:0px;"><span style="margin-top:0px;color:rgb(127 , 127 , 127);font-size:12px;">↵ &nbsp; &nbsp; &nbsp;3、 本专栏为虚拟内容服务，购买成功后不支持退款，请你理解。 &nbsp; &nbsp;</span>↵ &nbsp;</p>',
    duration: 60,
    displayType: 0,
    examFrequency: {},
    joinUserAvatars: [
      'https://img01.yzcdn.cn/upload_files/2020/05/19/FnIB9NM44636l0mW4E5MUtYy00Hr.png',
      'https://img01.yzcdn.cn/upload_files/2020/05/19/FnIB9NM44636l0mW4E5MUtYy00Hr.png',
      'https://img01.yzcdn.cn/upload_files/2020/05/19/FnIB9NM44636l0mW4E5MUtYy00Hr.png',
      'https://img01.yzcdn.cn/upload_files/2020/05/19/FnIB9NM44636l0mW4E5MUtYy00Hr.png',
    ],
    openCourseSettingDetail: true,
    publishType: 1,
    picture: {
      coverUrl: 'https://img01.yzcdn.cn/upload_files/2020/05/19/FnIB9NM44636l0mW4E5MUtYy00Hr.png',
      picWidth: 300,
      picHeight: 300,
      picId: 0,
    },
    questionCount: 20,
    questionIds: [0],
    status: ExamStatus.STARTED,
    totalScore: 100,
    title: '测试考试标题测试考试标题测试考试标题测试考试标题测试考试标题测试考试标题测试考试标题测试考试标题',
    timerPublishAt: 0,
    validity: {},
  },
  userJoinInfo: {
    canJoinExamStudentIds: [0, 1, 2],
    canRejoinCount: 1,
    canJoinExam: true,
    joinUserCount: 0,
    nextRejoinSeconds: 3600000,
    userExamStatus: UserExamStatus.NOT_JOIN,
  },
});

export const getCourseListData = Promise.resolve({
  content: [
    {
      alias: 'abc',
      kdtId: 0,
      courseType: 1,
      mediaType: 1,
      cover: 'https://img01.yzcdn.cn/upload_files/2020/05/19/FnIB9NM44636l0mW4E5MUtYy00Hr.png',
      title: '测试标题长度哈哈哈哈哈哈哈哈哈哈或或或或或或',
      price: 37800,
      subscriptionCount: 10,
    },
    {
      alias: 'abc',
      kdtId: 0,
      courseType: 1,
      mediaType: 1,
      cover: 'https://img01.yzcdn.cn/upload_files/2020/05/19/FnIB9NM44636l0mW4E5MUtYy00Hr.png',
      title: '测试标题长度哈哈哈哈哈哈哈哈哈哈或或或或或或',
      price: 37800,
      subscriptionCount: 10,
    },
    {
      alias: 'abc',
      kdtId: 0,
      courseType: 1,
      mediaType: 1,
      cover: 'https://img01.yzcdn.cn/upload_files/2020/05/19/FnIB9NM44636l0mW4E5MUtYy00Hr.png',
      title: '测试标题长度哈哈哈哈哈哈哈哈哈哈或或或或或或',
      price: 37800,
      subscriptionCount: 10,
    },
    {
      alias: 'abc',
      kdtId: 0,
      courseType: 1,
      mediaType: 1,
      cover: 'https://img01.yzcdn.cn/upload_files/2020/05/19/FnIB9NM44636l0mW4E5MUtYy00Hr.png',
      title: '测试标题长度哈哈哈哈哈哈哈哈哈哈或或或或或或',
      price: 37800,
      subscriptionCount: 10,
    },
    {
      alias: 'abc',
      kdtId: 0,
      courseType: 1,
      mediaType: 1,
      cover: 'https://img01.yzcdn.cn/upload_files/2020/05/19/FnIB9NM44636l0mW4E5MUtYy00Hr.png',
      title: '测试标题长度哈哈哈哈哈哈哈哈哈哈或或或或或或',
      price: 37800,
      subscriptionCount: 10,
    },
    {
      alias: 'abc',
      kdtId: 0,
      courseType: 1,
      mediaType: 1,
      cover: 'https://img01.yzcdn.cn/upload_files/2020/05/19/FnIB9NM44636l0mW4E5MUtYy00Hr.png',
      title: '测试标题长度哈哈哈哈哈哈哈哈哈哈或或或或或或',
      price: 37800,
      subscriptionCount: 10,
    },
    {
      alias: 'abc',
      kdtId: 0,
      courseType: 1,
      mediaType: 1,
      cover: 'https://img01.yzcdn.cn/upload_files/2020/05/19/FnIB9NM44636l0mW4E5MUtYy00Hr.png',
      title: '测试标题长度哈哈哈哈哈哈哈哈哈哈或或或或或或',
      price: 37800,
      subscriptionCount: 10,
    },
    {
      alias: 'abc',
      kdtId: 0,
      courseType: 1,
      mediaType: 1,
      cover: 'https://img01.yzcdn.cn/upload_files/2020/05/19/FnIB9NM44636l0mW4E5MUtYy00Hr.png',
      title: '测试标题长度哈哈哈哈哈哈哈哈哈哈或或或或或或',
      price: 37800,
      subscriptionCount: 10,
    },
    {
      alias: 'abc',
      kdtId: 0,
      courseType: 1,
      mediaType: 1,
      cover: 'https://img01.yzcdn.cn/upload_files/2020/05/19/FnIB9NM44636l0mW4E5MUtYy00Hr.png',
      title: '测试标题长度哈哈哈哈哈哈哈哈哈哈或或或或或或',
      price: 37800,
      subscriptionCount: 10,
    },
    {
      alias: 'abc',
      kdtId: 0,
      courseType: 1,
      mediaType: 1,
      cover: 'https://img01.yzcdn.cn/upload_files/2020/05/19/FnIB9NM44636l0mW4E5MUtYy00Hr.png',
      title: '测试标题长度哈哈哈哈哈哈哈哈哈哈或或或或或或',
      price: 37800,
      subscriptionCount: 10,
    },
  ],
  pageable: {
    totalPages: 10,
  },
  total: 130,
});

export const getStudentListData = Promise.resolve([
  {
    alias: '',
    address: '',
    avatar: '',
    age: '',
    bornDate: '',
    createUserId: 0,
    customAttributeItems: [],
    canDelete: 0,
    customer: {},
    gender: 1,
    grade: '',
    idCardNo: '',
    id: 0,
    lastClassTime: '',
    mobile: '13788889999',
    monthAge: '',
    name: '王同学',
    nickName: '王同学',
    phoneNumber: '13788889999',
    school: '',
    studentNo: '',
    userId: 0,
    wechatAccount: '',
  },
]);

export const getRecommendListData = Promise.resolve({
  total: 1,
  pageable: {},
  content: [
    {
      alias: '',
      cover: 'https://img01.yzcdn.cn/upload_files/2020/05/19/FnIB9NM44636l0mW4E5MUtYy00Hr.png',
      courseType: OwlType.COLUMN,
      mediaType: MediaType.AUDIO,
      kdtId: 0,
      title: '测试标题测试标题',
      price: 0,
      sales: 1,
      url: 'https://img01.yzcdn.cn/upload_files/2020/05/19/FnIB9NM44636l0mW4E5MUtYy00Hr.png',
    },
    {
      alias: '',
      cover: 'https://img01.yzcdn.cn/upload_files/2020/05/19/FnIB9NM44636l0mW4E5MUtYy00Hr.png',
      courseType: OwlType.COLUMN,
      mediaType: MediaType.AUDIO,
      kdtId: 0,
      title: '测试标题测试标题',
      price: 0,
      sales: 1,
      url: 'https://img01.yzcdn.cn/upload_files/2020/05/19/FnIB9NM44636l0mW4E5MUtYy00Hr.png',
    },
    {
      alias: '',
      cover: 'https://img01.yzcdn.cn/upload_files/2020/05/19/FnIB9NM44636l0mW4E5MUtYy00Hr.png',
      courseType: OwlType.COLUMN,
      mediaType: MediaType.AUDIO,
      kdtId: 0,
      title: '测试标题测试标题',
      price: 0,
      sales: 1,
      url: 'https://img01.yzcdn.cn/upload_files/2020/05/19/FnIB9NM44636l0mW4E5MUtYy00Hr.png',
    },
    {
      alias: '',
      cover: 'https://img01.yzcdn.cn/upload_files/2020/05/19/FnIB9NM44636l0mW4E5MUtYy00Hr.png',
      courseType: OwlType.COLUMN,
      mediaType: MediaType.AUDIO,
      kdtId: 0,
      title: '测试标题测试标题',
      price: 0,
      sales: 1,
      url: 'https://img01.yzcdn.cn/upload_files/2020/05/19/FnIB9NM44636l0mW4E5MUtYy00Hr.png',
    },
    {
      alias: '',
      cover: 'https://img01.yzcdn.cn/upload_files/2020/05/19/FnIB9NM44636l0mW4E5MUtYy00Hr.png',
      courseType: OwlType.COLUMN,
      mediaType: MediaType.AUDIO,
      kdtId: 0,
      title: '测试标题测试标题',
      price: 0,
      sales: 1,
      url: 'https://img01.yzcdn.cn/upload_files/2020/05/19/FnIB9NM44636l0mW4E5MUtYy00Hr.png',
    },
    {
      alias: '',
      cover: 'https://img01.yzcdn.cn/upload_files/2020/05/19/FnIB9NM44636l0mW4E5MUtYy00Hr.png',
      courseType: OwlType.COLUMN,
      mediaType: MediaType.AUDIO,
      kdtId: 0,
      title: '测试标题测试标题',
      price: 0,
      sales: 1,
      url: 'https://img01.yzcdn.cn/upload_files/2020/05/19/FnIB9NM44636l0mW4E5MUtYy00Hr.png',
    },
  ],
});

export const getLatestQuestionData = Promise.resolve({
  // answerTexts: ['a', 'b', 'c'],
  answerTexts: ['精神小伙，原指收拾的十分利落，看起来充满活力、很有精神的小伙子。现在几乎特指看起来很社会的土味小伙子，具体表现有：整条胳膊的纹身、颜色不限的锅盖头、紧身的裤子、锃光瓦亮的豆豆鞋、动感十足的社会摇、霸气无比的社会语录等。'],
  correct: true,
  chooseOptionIds: ['1', '2'],
  currentQuestionId: '0',
  expireExamEndTime: true,
  examTitle: 'testsetestset',
  fillCount: 3,
  question: {
    group: '',
    isOrdered: true,
    id: 0,
    kdtId: 0,
    level: 0,
    options: [
      { content: 'TURE' },
      { content: 'FALSE' },
    ],
    // options: [
    //   { optionId: '0', content: '<p>图文更让他和让他好还没好</p><p><iframe frameborder="0" src="https://v.qq.com/txp/iframe/player.html?vid=c0972smonuc" allowFullScreen="true"></iframe><img data-origin-width="750" data-origin-height="1334" src="https://img01.yzcdn.cn/upload_files/2020/03/05/Frw3G7d3thXby8ZDcMlygVNN_m-h.png!730x0.jpg"/></p>图文更让他和让他好还没好<p>图文更让他和让他好还没好</p>' },
    //   { optionId: '1', content: '<p>test1</p><p><img data-origin-width="750" data-origin-height="1334" src="https://img01.yzcdn.cn/upload_files/2020/03/05/Frw3G7d3thXby8ZDcMlygVNN_m-h.png!730x0.jpg"/</p><p><img data-origin-width="750" data-origin-height="1334" src="https://img01.yzcdn.cn/upload_files/2020/03/05/Frw3G7d3thXby8ZDcMlygVNN_m-h.png!730x0.jpg"/</p>' },
    //   { optionId: '2', content: '<p>test1</p><p><img data-origin-width="750" data-origin-height="1334" src="https://img01.yzcdn.cn/upload_files/2020/03/05/Frw3G7d3thXby8ZDcMlygVNN_m-h.png!730x0.jpg"/</p>' },
    //   { optionId: '4', content: '<p>test1</p>' },
    // ],
    score: 2,
    serialNo: 1,
    // content: '<p>图文更让他和让他好还没好图文更让他和让他好还没好图文更让他和让他好还没好图文更让他和让他好还没好图文更让他和让他好还没好图文更让他和让他好还没好图文更让他和让他好还没好图文更让他和让他好还没好<img data-origin-width="750" data-origin-height="1334" src="https://img01.yzcdn.cn/upload_files/2020/03/05/Frw3G7d3thXby8ZDcMlygVNN_m-h.png!730x0.jpg" /></p>',
    // content: '<p>图文更让他和让他好<img data-origin-width="750" data-origin-height="1334" src="https://img01.yzcdn.cn/upload_files/2020/03/05/Frw3G7d3thXby8ZDcMlygVNN_m-h.png!730x0.jpg" /></p>',
    // title: '<p>图文更让他和让他好还没好</p><p><iframe class="edui-faked-video" src="https://v.qq.com/iframe/player.html?vid=c0972smonuc&tiny=0&auto=0" width="300" height="225" allowfullscreen="true"></iframe></p><p><img data-origin-width="750" data-origin-height="1334" src="https://img01.yzcdn.cn/upload_files/2020/03/05/Frw3G7d3thXby8ZDcMlygVNN_m-h.png!730x0.jpg"/></p>',
    title: '<p>这个填空题有三个空，1 2 3 哈哈哈</p>',
    type: QuestionType.SUBJECTIVE,
  },
  serialNo: 0,
  userAnswerReview: {
    correct: false,
    examAnswer: {
      // answers: ['0', '1'],
      answers: ['a', 'b', 'd'],
      analysis: '<p>图文更让他和让他好还没好</p><p><iframe class="edui-faked-video" src="https://v.qq.com/iframe/player.html?vid=c0972smonuc&tiny=0&auto=0" width="300" height="225" allowfullscreen="true"></iframe></p><p><img data-origin-width="750" data-origin-height="1334" src="https://img01.yzcdn.cn/upload_files/2020/03/05/Frw3G7d3thXby8ZDcMlygVNN_m-h.png!730x0.jpg"/></p>',
      grading: {},
      kdtId: 0,
      questionId: 0,
    },
    review: {
      comment: '<p>图文更让他和让他好还没好</p><p><iframe class="edui-faked-video" src="https://v.qq.com/iframe/player.html?vid=c0972smonuc&tiny=0&auto=0" width="300" height="225" allowfullscreen="true"></iframe></p><p><img data-origin-width="750" data-origin-height="1334" src="https://img01.yzcdn.cn/upload_files/2020/03/05/Frw3G7d3thXby8ZDcMlygVNN_m-h.png!730x0.jpg"/></p>',
      questionId: 0,
      score: 0,
    },
    score: 2,
    userAnswer: {
      correct: false,
      contents: [''],
      options: [''],
    },
  },
  userExamDTO: {
    endTime: '',
    examId: 0,
    inThisExam: true,
    joinStartTime: '',
    joinEndTime: '',
    kdtId: 0,
    remainMillisecond: 0,
    startTime: '',
    state: 0,
    userExamId: 0,
    userId: 0,
  },
});

export const getPrevQuestionData = Promise.resolve({
  // answerTexts: ['a', 'b', 'c'],
  answerTexts: ['精神小伙，原指收拾的十分利落，看起来充满活力、很有精神的小伙子。现在几乎特指看起来很社会的土味小伙子，具体表现有：整条胳膊的纹身、颜色不限的锅盖头、紧身的裤子、锃光瓦亮的豆豆鞋、动感十足的社会摇、霸气无比的社会语录等。'],
  correct: true,
  chooseOptionIds: ['1', '2'],
  currentQuestionId: '0',
  expireExamEndTime: true,
  examTitle: 'testsetestset',
  fillCount: 3,
  question: {
    group: '',
    isOrdered: true,
    id: 0,
    kdtId: 0,
    level: 0,
    options: [
      { content: 'TURE' },
      { content: 'FALSE' },
    ],
    // options: [
    //   { optionId: '0', content: '<p>图文更让他和让他好还没好</p><p><iframe frameborder="0" src="https://v.qq.com/txp/iframe/player.html?vid=c0972smonuc" allowFullScreen="true"></iframe><img data-origin-width="750" data-origin-height="1334" src="https://img01.yzcdn.cn/upload_files/2020/03/05/Frw3G7d3thXby8ZDcMlygVNN_m-h.png!730x0.jpg"/></p>图文更让他和让他好还没好<p>图文更让他和让他好还没好</p>' },
    //   { optionId: '1', content: '<p>test1</p><p><img data-origin-width="750" data-origin-height="1334" src="https://img01.yzcdn.cn/upload_files/2020/03/05/Frw3G7d3thXby8ZDcMlygVNN_m-h.png!730x0.jpg"/</p><p><img data-origin-width="750" data-origin-height="1334" src="https://img01.yzcdn.cn/upload_files/2020/03/05/Frw3G7d3thXby8ZDcMlygVNN_m-h.png!730x0.jpg"/</p>' },
    //   { optionId: '2', content: '<p>test1</p><p><img data-origin-width="750" data-origin-height="1334" src="https://img01.yzcdn.cn/upload_files/2020/03/05/Frw3G7d3thXby8ZDcMlygVNN_m-h.png!730x0.jpg"/</p>' },
    //   { optionId: '4', content: '<p>test1</p>' },
    // ],
    score: 2,
    serialNo: 1,
    // content: '<p>图文更让他和让他好还没好图文更让他和让他好还没好图文更让他和让他好还没好图文更让他和让他好还没好图文更让他和让他好还没好图文更让他和让他好还没好图文更让他和让他好还没好图文更让他和让他好还没好<img data-origin-width="750" data-origin-height="1334" src="https://img01.yzcdn.cn/upload_files/2020/03/05/Frw3G7d3thXby8ZDcMlygVNN_m-h.png!730x0.jpg" /></p>',
    // content: '<p>图文更让他和让他好<img data-origin-width="750" data-origin-height="1334" src="https://img01.yzcdn.cn/upload_files/2020/03/05/Frw3G7d3thXby8ZDcMlygVNN_m-h.png!730x0.jpg" /></p>',
    // title: '<p>图文更让他和让他好还没好</p><p><iframe class="edui-faked-video" src="https://v.qq.com/iframe/player.html?vid=c0972smonuc&tiny=0&auto=0" width="300" height="225" allowfullscreen="true"></iframe></p><p><img data-origin-width="750" data-origin-height="1334" src="https://img01.yzcdn.cn/upload_files/2020/03/05/Frw3G7d3thXby8ZDcMlygVNN_m-h.png!730x0.jpg"/></p>',
    title: '<p>这是上一题</p>',
    type: QuestionType.SUBJECTIVE,
  },
  serialNo: 0,
  userAnswerReview: {
    correct: false,
    examAnswer: {
      // answers: ['0', '1'],
      answers: ['a', 'b', 'd'],
      analysis: '<p>图文更让他和让他好还没好</p><p><iframe class="edui-faked-video" src="https://v.qq.com/iframe/player.html?vid=c0972smonuc&tiny=0&auto=0" width="300" height="225" allowfullscreen="true"></iframe></p><p><img data-origin-width="750" data-origin-height="1334" src="https://img01.yzcdn.cn/upload_files/2020/03/05/Frw3G7d3thXby8ZDcMlygVNN_m-h.png!730x0.jpg"/></p>',
      grading: {},
      kdtId: 0,
      questionId: 0,
    },
    review: {
      comment: '<p>图文更让他和让他好还没好</p><p><iframe class="edui-faked-video" src="https://v.qq.com/iframe/player.html?vid=c0972smonuc&tiny=0&auto=0" width="300" height="225" allowfullscreen="true"></iframe></p><p><img data-origin-width="750" data-origin-height="1334" src="https://img01.yzcdn.cn/upload_files/2020/03/05/Frw3G7d3thXby8ZDcMlygVNN_m-h.png!730x0.jpg"/></p>',
      questionId: 0,
      score: 0,
    },
    score: 2,
    userAnswer: {
      correct: false,
      contents: [''],
      options: [''],
    },
  },
  userExamDTO: {
    endTime: '',
    examId: 0,
    inThisExam: true,
    joinStartTime: '',
    joinEndTime: '',
    kdtId: 0,
    remainMillisecond: 0,
    startTime: '',
    state: 0,
    userExamId: 0,
    userId: 0,
  },
});

export const getNextQuestionData = Promise.resolve({
  // answerTexts: ['a', 'b', 'c'],
  answerTexts: ['精神小伙，原指收拾的十分利落，看起来充满活力、很有精神的小伙子。现在几乎特指看起来很社会的土味小伙子，具体表现有：整条胳膊的纹身、颜色不限的锅盖头、紧身的裤子、锃光瓦亮的豆豆鞋、动感十足的社会摇、霸气无比的社会语录等。'],
  correct: true,
  chooseOptionIds: ['1', '2'],
  currentQuestionId: '0',
  expireExamEndTime: true,
  examTitle: 'testsetestset',
  fillCount: 3,
  question: {
    group: '',
    isOrdered: true,
    id: 0,
    kdtId: 0,
    level: 0,
    // options: [
    //   { content: 'TURE' },
    //   { content: 'FALSE' },
    // ],
    options: [
      { optionId: '0', content: '<p>图文更让他和让他好还没好</p><p><iframe frameborder="0" src="https://v.qq.com/txp/iframe/player.html?vid=c0972smonuc" allowFullScreen="true"></iframe><img data-origin-width="750" data-origin-height="1334" src="https://img01.yzcdn.cn/upload_files/2020/03/05/Frw3G7d3thXby8ZDcMlygVNN_m-h.png!730x0.jpg"/></p>图文更让他和让他好还没好<p>图文更让他和让他好还没好</p>' },
      { optionId: '1', content: '<p>test1</p><p><img data-origin-width="750" data-origin-height="1334" src="https://img01.yzcdn.cn/upload_files/2020/03/05/Frw3G7d3thXby8ZDcMlygVNN_m-h.png!730x0.jpg"/</p><p><img data-origin-width="750" data-origin-height="1334" src="https://img01.yzcdn.cn/upload_files/2020/03/05/Frw3G7d3thXby8ZDcMlygVNN_m-h.png!730x0.jpg"/</p>' },
      { optionId: '2', content: '<p>test1</p><p><img data-origin-width="750" data-origin-height="1334" src="https://img01.yzcdn.cn/upload_files/2020/03/05/Frw3G7d3thXby8ZDcMlygVNN_m-h.png!730x0.jpg"/</p>' },
      { optionId: '4', content: '<p>test1</p>' },
    ],
    score: 2,
    serialNo: 1,
    content: '<p>这是下一题图文更让他和让他好还没好图文更让他和让他好还没好图文更让他和让他好还没好图文更让他和让他好还没好图文更让他和让他好还没好图文更让他和让他好还没好图文更让他和让他好还没好图文更让他和让他好还没好<img data-origin-width="750" data-origin-height="1334" src="https://img01.yzcdn.cn/upload_files/2020/03/05/Frw3G7d3thXby8ZDcMlygVNN_m-h.png!730x0.jpg" /></p>',
    // content: '<p>图文更让他和让他好<img data-origin-width="750" data-origin-height="1334" src="https://img01.yzcdn.cn/upload_files/2020/03/05/Frw3G7d3thXby8ZDcMlygVNN_m-h.png!730x0.jpg" /></p>',
    title: '<p>这是下一题图文更让他和让他好还没好</p><p><iframe class="edui-faked-video" src="https://v.qq.com/iframe/player.html?vid=c0972smonuc&tiny=0&auto=0" width="300" height="225" allowfullscreen="true"></iframe></p><p><img data-origin-width="750" data-origin-height="1334" src="https://img01.yzcdn.cn/upload_files/2020/03/05/Frw3G7d3thXby8ZDcMlygVNN_m-h.png!730x0.jpg"/></p>',
    type: QuestionType.MULTIPLE,
  },
  serialNo: 0,
  userAnswerReview: {
    correct: false,
    examAnswer: {
      answers: ['0', '1'],
      // answers: ['a', 'b', 'd'],
      analysis: '<p>图文更让他和让他好还没好</p><p><iframe class="edui-faked-video" src="https://v.qq.com/iframe/player.html?vid=c0972smonuc&tiny=0&auto=0" width="300" height="225" allowfullscreen="true"></iframe></p><p><img data-origin-width="750" data-origin-height="1334" src="https://img01.yzcdn.cn/upload_files/2020/03/05/Frw3G7d3thXby8ZDcMlygVNN_m-h.png!730x0.jpg"/></p>',
      grading: {},
      kdtId: 0,
      questionId: 0,
    },
    review: {
      comment: '<p>图文更让他和让他好还没好</p><p><iframe class="edui-faked-video" src="https://v.qq.com/iframe/player.html?vid=c0972smonuc&tiny=0&auto=0" width="300" height="225" allowfullscreen="true"></iframe></p><p><img data-origin-width="750" data-origin-height="1334" src="https://img01.yzcdn.cn/upload_files/2020/03/05/Frw3G7d3thXby8ZDcMlygVNN_m-h.png!730x0.jpg"/></p>',
      questionId: 0,
      score: 0,
    },
    score: 2,
    userAnswer: {
      correct: false,
      contents: [''],
      options: [''],
    },
  },
  userExamDTO: {
    endTime: '',
    examId: 0,
    inThisExam: true,
    joinStartTime: '',
    joinEndTime: '',
    kdtId: 0,
    remainMillisecond: 0,
    startTime: '',
    state: 0,
    userExamId: 0,
    userId: 0,
  },
});

export const getAnswerCardData = Promise.resolve({
  answerCard: {
    correctNum: 0,
    errorNum: 0,
    questionCount: 60,
    questions: [
      {
        correct: true,
        questionId: 0,
        type: 1,
        answered: true,
      },
      {
        correct: true,
        questionId: 0,
        type: 2,
        answered: false,
      },
      {
        correct: true,
        questionId: 0,
        type: 2,
        answered: true,
      },
      {
        correct: true,
        questionId: 0,
        type: 1,
        answered: true,
      },
      {
        correct: false,
        questionId: 0,
        type: 2,
        answered: true,
      },
      {
        correct: false,
        questionId: 0,
        type: 1,
        answered: true,
      },
      {
        correct: true,
        questionId: 0,
        type: 2,
        answered: false,
      },
      {
        correct: true,
        questionId: 0,
        type: 2,
        answered: false,
      },
      {
        correct: true,
        questionId: 0,
        type: 2,
        answered: false,
      },
      {
        correct: true,
        questionId: 0,
        type: 2,
        answered: false,
      },
      {
        correct: true,
        questionId: 0,
        type: 2,
        answered: false,
      },
      {
        correct: true,
        questionId: 0,
        type: 2,
        answered: false,
      },
      {
        correct: true,
        questionId: 0,
        type: 2,
        answered: false,
      },
      {
        correct: true,
        questionId: 0,
        type: 2,
        answered: false,
      },
      {
        correct: true,
        questionId: 0,
        type: 2,
        answered: false,
      },
      {
        correct: true,
        questionId: 0,
        type: 2,
        answered: false,
      },
      {
        correct: true,
        questionId: 0,
        type: 2,
        answered: false,
      },
      {
        correct: true,
        questionId: 0,
        type: 2,
        answered: false,
      },
      {
        correct: true,
        questionId: 0,
        type: 2,
        answered: false,
      },
      {
        correct: true,
        questionId: 0,
        type: 2,
        answered: false,
      },
      {
        correct: true,
        questionId: 0,
        type: 2,
        answered: false,
      },
      {
        correct: true,
        questionId: 0,
        type: 2,
        answered: false,
      },
      {
        correct: true,
        questionId: 0,
        type: 2,
        answered: false,
      },
      {
        correct: true,
        questionId: 0,
        type: 2,
        answered: false,
      },
      {
        correct: true,
        questionId: 0,
        type: 2,
        answered: false,
      },
      {
        correct: true,
        questionId: 0,
        type: 2,
        answered: false,
      },
      {
        correct: true,
        questionId: 0,
        type: 2,
        answered: false,
      },
      {
        correct: true,
        questionId: 0,
        type: 2,
        answered: false,
      },
      {
        correct: true,
        questionId: 0,
        type: 2,
        answered: false,
      },
      {
        correct: true,
        questionId: 0,
        type: 2,
        answered: false,
      },
      {
        correct: true,
        questionId: 0,
        type: 2,
        answered: false,
      },
      {
        correct: true,
        questionId: 0,
        type: 2,
        answered: false,
      },
      {
        correct: true,
        questionId: 0,
        type: 2,
        answered: false,
      },
      {
        correct: true,
        questionId: 0,
        type: 2,
        answered: false,
      },
      {
        correct: true,
        questionId: 0,
        type: 2,
        answered: false,
      },
      {
        correct: true,
        questionId: 0,
        type: 2,
        answered: false,
      },
      {
        correct: true,
        questionId: 0,
        type: 2,
        answered: false,
      },
      {
        correct: true,
        questionId: 0,
        type: 2,
        answered: false,
      },
      {
        correct: true,
        questionId: 0,
        type: 2,
        answered: false,
      },
      {
        correct: true,
        questionId: 0,
        type: 2,
        answered: false,
      },
      {
        correct: true,
        questionId: 0,
        type: 2,
        answered: false,
      },
      {
        correct: true,
        questionId: 0,
        type: 2,
        answered: false,
      },
      {
        correct: true,
        questionId: 0,
        type: 2,
        answered: false,
      },
      {
        correct: true,
        questionId: 0,
        type: 2,
        answered: false,
      },
      {
        correct: true,
        questionId: 0,
        type: 2,
        answered: false,
      },
      {
        correct: true,
        questionId: 0,
        type: 2,
        answered: false,
      },
      {
        correct: true,
        questionId: 0,
        type: 2,
        answered: false,
      },
      {
        correct: true,
        questionId: 0,
        type: 2,
        answered: false,
      },
      {
        correct: true,
        questionId: 0,
        type: 2,
        answered: false,
      },
      {
        correct: true,
        questionId: 0,
        type: 2,
        answered: false,
      },
      {
        correct: true,
        questionId: 0,
        type: 2,
        answered: false,
      },
      {
        correct: true,
        questionId: 0,
        type: 2,
        answered: false,
      },
      {
        correct: true,
        questionId: 0,
        type: 2,
        answered: false,
      },
      {
        correct: true,
        questionId: 0,
        type: 2,
        answered: false,
      },
      {
        correct: true,
        questionId: 0,
        type: 2,
        answered: false,
      },
      {
        correct: true,
        questionId: 0,
        type: 2,
        answered: false,
      },
      {
        correct: true,
        questionId: 0,
        type: 2,
        answered: false,
      },
      {
        correct: true,
        questionId: 0,
        type: 2,
        answered: false,
      },
    ],
    subjectNum: 0,
    unansweredNum: 59,
  },
  userExam: {
    endTime: 0,
    examId: 0,
    inThisExam: false,
    joinStartTime: 0,
    joinEndTime: 0,
    kdtId: 0,
    remainMillisecond: 0,
    startTime: 0,
    userExamId: 0,
    userId: 0,
  },
});
