module.exports = [
  [
    'POST',
    '/v4/vis/course/live/live-selling/createCoupon.json',
    'course.live.LiveSellingController',
    'postCreateCouponJson',
  ],
  [
    'GET',
    '/v4/vis/course/live/live-selling/findCouponList.json',
    'course.live.LiveSellingController',
    'getFindCouponListJson',
  ],
  [
    'GET',
    '/v4/vis/course/live/live-selling/findPage.json',
    'course.live.LiveSellingController',
    'getFindPageJson',
  ],
  [
    'GET',
    '/v4/vis/course/live/live-selling/getLiveMarketingDashboardInfo.json',
    'course.live.LiveSellingController',
    'getGetLiveMarketingDashboardInfoJson',
  ],
  [
    'POST',
    '/v4/vis/course/live/live-selling/saveGoods.json',
    'course.live.LiveSellingController',
    'postSaveJson',
  ],
  [
    'POST',
    '/v4/vis/course/live/live-selling/removeGoods.json',
    'course.live.LiveSellingController',
    'postRemoveJson',
  ],
  [
    'POST',
    '/v4/vis/course/live/live-selling/createCoupon.json',
    'course.live.LiveSellingController',
    'postCreateCouponJson',
  ],
  [
    'POST',
    '/v4/vis/course/live/live-selling/deleteCoupon.json',
    'course.live.LiveSellingController',
    'postDeleteCouponJson',
  ],
  [
    'POST',
    '/v4/vis/course/live/live-selling/updateLiveMarketingSetting.json',
    'course.live.LiveSellingController',
    'postUpdateLiveMarketingSettingJson',
  ],
];
