module.exports = [
  ['GET', '/v4/vis/h5/edu/clue/clue-detail', 'h5.clueDetail.IndexController', 'getIndexHtml'],
  ['GET', '/v4/vis/h5/edu/clue/clue-detail/select-order', 'h5.clueDetail.IndexController', 'getIndexHtml'],
  ['GET', '/v4/vis/h5/edu/clue/edit-tag', 'h5.clueDetail.IndexController', 'getIndexHtml'],
  ['GET', '/v4/vis/h5/edu/clue/record-detail', 'h5.clueDetail.IndexController', 'getIndexHtml'],
  ['GET', '/v4/vis/h5/edu/clue/student-info', 'h5.clueDetail.IndexController', 'getIndexHtml'],
  ['GET', '/v4/vis/h5/edu/clue/clue-tag', 'h5.clueDetail.IndexController', 'getIndexHtml'],
  ['GET', '/v4/vis/h5/edu/clue/signup-detail', 'h5.clueDetail.IndexController', 'getIndexHtml'],
  ['GET', '/v4/vis/h5/edu/clue/update-dynamic', 'h5.clueDetail.IndexController', 'getIndexHtml'],
  ['GET', '/v4/vis/h5/edu/clue/getDetailById.json', 'h5.clueDetail.IndexController', 'getDetailById'],
  ['GET', '/v4/vis/h5/edu/clue/getClueSetting.json', 'h5.clueDetail.IndexController', 'getClueSetting'],
  ['GET', '/v4/vis/h5/edu/clue/findStudentLessonsForClue.json', 'h5.clueDetail.IndexController', 'findStudentLessonsForClue'],
  ['GET', '/v4/vis/h5/edu/clue/findStudentLessonsByIdentity.json', 'h5.clueDetail.IndexController', 'findStudentLessonsByIdentity'],
  ['GET', '/v4/vis/h5/edu/clue/findPageByMobileWithCourse.json', 'h5.clueDetail.IndexController', 'findPageByMobileWithCourse'],
  ['GET', '/v4/vis/h5/edu/clue/findPageClueRecords.json', 'h5.clueDetail.IndexController', 'findPageClueRecords'],
  ['GET', '/v4/vis/h5/edu/clue/queryRelatedOrder.json', 'h5.clueDetail.IndexController', 'queryRelatedOrder'],
  ['GET', '/v4/vis/h5/edu/clue/getNextDetailById.json', 'h5.clueDetail.IndexController', 'getNextDetailById'],
  ['POST', '/v4/vis/h5/edu/clue/cancelAppointment.json', 'h5.clueDetail.IndexController', 'cancelAppointment'],
  ['POST', '/v4/vis/h5/edu/clue/changeState.json', 'h5.clueDetail.IndexController', 'changeState'],
  ['POST', '/v4/vis/h5/edu/clue/createPreAppointment.json', 'h5.clueDetail.IndexController', 'createPreAppointment'],
  ['POST', '/v4/vis/h5/edu/clue/createPreAppointmentForClue.json', 'h5.clueDetail.IndexController', 'createPreAppointmentForClue'],
  ['POST', '/v4/vis/h5/edu/clue/distributeClues.json', 'h5.clueDetail.IndexController', 'distributeClues'],
  ['POST', '/v4/vis/h5/edu/clue/createClueRecord.json', 'h5.clueDetail.IndexController', 'createClueRecord'],
  ['POST', '/v4/vis/h5/edu/clue/updateClueRecord.json', 'h5.clueDetail.IndexController', 'updateClueRecord'],
];
