module.exports = [
  ['快递发货首页', 'GET', '/v4/trade/express(.*)', 'express.ExpressController', 'getExpressHtml'],
  ['GET', '/v4/trade/api/express/templates', 'express.ExpressController', 'listTemplates'],
  ['GET', '/v4/trade/api/express/template', 'express.ExpressController', 'getTemplateDetail'],
  ['GET', '/v4/trade/api/express/template/replicate', 'express.ExpressController', 'replicate'],
  [
    'POST',
    '/v4/trade/api/express/template/replicate',
    'express.ExpressController',
    'replicatePost',
  ],
  ['POST', '/v4/trade/api/express/template', 'express.ExpressController', 'create'],
  ['PATCH', '/v4/trade/api/express/template', 'express.ExpressController', 'update'],
  ['DELETE', '/v4/trade/api/express/template', 'express.ExpressController', 'deleteTemp'],
  ['GET', '/v4/trade/api/express/setting', 'express.ExpressController', 'getSettingV3'],
  ['POST', '/v4/trade/api/express/setting', 'express.ExpressController', 'updateSetting'],
  ['GET', '/v4/trade/api/express/tradeSetting', 'express.ExpressController', 'getTradeSetting'],
  ['GET', '/v4/trade/api/express/region', 'express.ExpressController', 'getRegionPartitions'],
  ['GET', '/v4/trade/api/express/regionmap', 'express.ExpressController', 'getAllIdNameMap'],
  [
    'GET',
    '/v4/trade/api/express/queryTicketprint',
    'express.ExpressController',
    'queryTicketprint',
  ],
  [
    'POST',
    '/v4/trade/api/express/updateTicketprint',
    'express.ExpressController',
    'updateTicketprint',
  ],
];
