module.exports = [
  [
    'GET',
    ['/v4/trade/review', '/v4/trade/review/index'],
    'review.ReviewController',
    'getIndexHtml',
  ],
  ['GET', '/v4/trade/review/getList.json', 'review.ReviewController', 'getReviewList'],
  ['POST', '/v4/trade/review/submit.json', 'review.ReviewController', 'submitReview'],
  ['GET', '/v4/trade/review/getStoreList.json', 'review.ReviewController', 'getStoreList'],
  ['置顶评论', 'POST', '/v4/trade/review/stick.json', 'review.ReviewController', 'stickReview'],
  [
    '取消置顶评论',
    'POST',
    '/v4/trade/review/unStick.json',
    'review.ReviewController',
    'unStickReview',
  ],
  [
    '加精评论',
    'POST',
    '/v4/trade/review/addExcellentEvaluation.json',
    'review.ReviewController',
    'addExcellentEvaluation',
  ],
  [
    '取消加精评论',
    'POST',
    '/v4/trade/review/cancelExcellentEvaluation.json',
    'review.ReviewController',
    'cancelExcellentEvaluation',
  ],
  [
    '获取买家秀状态',
    'GET',
    '/v4/trade/review/queryBuyersShowStatus.json',
    'review.ReviewController',
    'queryBuyersShowStatus',
  ],
];
